export const TOGGLE_MAIN_NAV_LINK = 'TOGGLE_MAIN_NAV_LINK'
export const DELETE_NAV_LINK = 'DELETE_NAV_LINK'
export const EDIT_NAV_LINK_TEXT = 'EDIT_NAV_LINK_TEXT'
export const TOGGLE_INPUT_EDIT = 'TOGGLE_INPUT_EDIT'