export const TOGGLE_MAIN_NAV_LINK = 'TOGGLE_MAIN_NAV_LINK'
export const DELETE_NAV_LINK = 'DELETE_NAV_LINK'
export const EDIT_NAV_LINK_TEXT = 'EDIT_NAV_LINK_TEXT'
export const TOGGLE_INPUT_EDIT = 'TOGGLE_INPUT_EDIT'

export const ADD_ALERT_ITEM = 'ADD_ALERT_ITEM'
export const DEL_ALERT_ITEM = 'DEL_ALERT_ITEM'
export const SORT_DATES_ALERTS_ITEM = 'SORT_DATES_ALERTS_ITEM'

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const EDITING_TRANSACTION = 'EDITING_TRANSACTION';

export const CREATE_DATA_TRANSACTION_DETAIL = 'CREATE_DATA_TRANSACTION_DETAIL';
export const DELETE_DATA_TRANSACTION_DETAIL = 'DELETE_DATA_TRANSACTION_DETAIL';

export const CREATE_SELECT_TRANSACTION_ITEM = ' CREATE_SELECT_TRANSACTION_ITEM';

export const CREATE_DATA_SEARCH_DETAIL_TRANSACTION = 'CREATE_DATA_SEARCH_DETAIL_TRANSACTION';

export const DELETE_DATA_SEARCH_DETAIL_TRANSACTION = 'DELETE_DATA_SEARCH_DETAIL_TRANSACTION';